using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LiteSql.CodeGen
{
    /// <summary>
    /// Generates C# source code from a DbmlModel, compatible with LiteSql.
    /// </summary>
    public static class CodeGenerator
    {
        /// <summary>
        /// Generates the complete C# file content for a DBML model.
        /// </summary>
        public static string Generate(DbmlModel model, string targetNamespace)
        {
            var sb = new StringBuilder();

            // File header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//   Generated by LiteSql.CodeGen from DBML");
            sb.AppendLine($"//   Database: {model.DatabaseName}");
            sb.AppendLine($"//   Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//   Changes to this file may be overwritten.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using LiteSql;");
            sb.AppendLine("using LiteSql.Mapping;");
            sb.AppendLine();
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");

            // Generate DataContext class
            GenerateContextClass(sb, model);

            // Generate entity classes
            foreach (var table in model.Tables)
            {
                sb.AppendLine();
                GenerateEntityClass(sb, table);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateContextClass(StringBuilder sb, DbmlModel model)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// LiteSql DataContext for {model.DatabaseName}.");
            sb.AppendLine($"    /// Generated from DBML. Inherits from LiteContext.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public partial class {model.ContextClassName} : LiteContext");
            sb.AppendLine("    {");

            // Constructors
            sb.AppendLine($"        public {model.ContextClassName}(IDbConnection connection) : base(connection) {{ }}");
            sb.AppendLine($"        public {model.ContextClassName}(string connectionString) : base(connectionString) {{ }}");
            sb.AppendLine();

            // Static factory method (common L2S pattern)
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Creates a new instance using ConnectionFactory.");
            sb.AppendLine($"        /// Set LiteContext.ConnectionFactory at app startup.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static {model.ContextClassName} New()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {model.ContextClassName}(DefaultConnectionString);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Default connection string. Set at app startup.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static string DefaultConnectionString {{ get; set; }}");
            sb.AppendLine();

            // Typed table properties
            foreach (var table in model.Tables)
            {
                sb.AppendLine($"        public Table<{table.TypeName}> {table.MemberName} => GetTable<{table.TypeName}>();");
            }

            sb.AppendLine("    }");
        }

        private static void GenerateEntityClass(StringBuilder sb, DbmlTable table)
        {
            sb.AppendLine($"    [Table(Name = \"{table.DbTableName}\")]");
            sb.AppendLine($"    public partial class {table.TypeName}");
            sb.AppendLine("    {");

            // Columns
            foreach (var col in table.Columns)
            {
                var attrs = new List<string>();
                attrs.Add($"Name = \"{col.Name}\"");
                attrs.Add($"DbType = \"{col.DbType}\"");

                if (col.IsPrimaryKey)
                    attrs.Add("IsPrimaryKey = true");
                if (col.IsDbGenerated)
                    attrs.Add("IsDbGenerated = true");

                attrs.Add($"CanBeNull = {(col.CanBeNull ? "true" : "false")}");

                sb.AppendLine($"        [Column({string.Join(", ", attrs)})]");

                var clrType = MapClrType(col.ClrType, col.CanBeNull);
                sb.AppendLine($"        public {clrType} {col.Name} {{ get; set; }}");
                sb.AppendLine();
            }

            // Associations (as comments/stubs for Phase 1)
            var navAssocs = table.Associations.Where(a => !a.IsForeignKey).ToList();
            var fkAssocs = table.Associations.Where(a => a.IsForeignKey).ToList();

            if (navAssocs.Any() || fkAssocs.Any())
            {
                sb.AppendLine("        #region Associations (navigation - not loaded by default)");
                sb.AppendLine();

                foreach (var assoc in fkAssocs)
                {
                    sb.AppendLine($"        // FK: {assoc.ThisKey} -> {assoc.OtherType}.{assoc.OtherKey}");
                    sb.AppendLine($"        [Association(Name = \"{assoc.Name}\", ThisKey = \"{assoc.ThisKey}\", OtherKey = \"{assoc.OtherKey}\", IsForeignKey = true)]");
                    sb.AppendLine($"        public {assoc.OtherType} {assoc.MemberName} {{ get; set; }}");
                    sb.AppendLine();
                }

                foreach (var assoc in navAssocs)
                {
                    sb.AppendLine($"        // Nav: {assoc.OtherType}.{assoc.OtherKey} -> {assoc.ThisKey}");
                    sb.AppendLine($"        [Association(Name = \"{assoc.Name}\", ThisKey = \"{assoc.ThisKey}\", OtherKey = \"{assoc.OtherKey}\")]");
                    sb.AppendLine($"        // public EntitySet<{assoc.OtherType}> {assoc.MemberName} {{ get; set; }}");
                    sb.AppendLine();
                }

                sb.AppendLine("        #endregion");
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// Maps System.* CLR type names to C# type keywords.
        /// Adds ? suffix for nullable value types.
        /// </summary>
        private static string MapClrType(string clrType, bool canBeNull)
        {
            var baseType = clrType switch
            {
                "System.Int16" => "short",
                "System.Int32" => "int",
                "System.Int64" => "long",
                "System.Boolean" => "bool",
                "System.Byte" => "byte",
                "System.Decimal" => "decimal",
                "System.Double" => "double",
                "System.Single" => "float",
                "System.DateTime" => "DateTime",
                "System.DateTimeOffset" => "DateTimeOffset",
                "System.TimeSpan" => "TimeSpan",
                "System.Guid" => "Guid",
                "System.String" => "string",
                "System.Byte[]" => "byte[]",
                "System.Data.Linq.Binary" => "byte[]",
                "System.Char" => "char",
                _ => clrType.StartsWith("System.") ? clrType.Substring(7) : clrType
            };

            // Add nullable suffix for value types that can be null
            if (canBeNull && IsValueType(baseType))
            {
                baseType += "?";
            }

            return baseType;
        }

        private static bool IsValueType(string type)
        {
            return type switch
            {
                "short" or "int" or "long" or "bool" or "byte" or
                "decimal" or "double" or "float" or "char" or
                "DateTime" or "DateTimeOffset" or "TimeSpan" or "Guid" => true,
                _ => false
            };
        }
    }
}
